# Generated by Django 3.2.9 on 2021-12-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('name_uk', models.CharField(max_length=32, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=32, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=32, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImgSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='картинка слайда', max_length=32, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('image_uk', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('image_ru', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('image_en', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('title_uk', models.CharField(max_length=32, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=32, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=32, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_uk', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('pieces', models.IntegerField(verbose_name='Кол. кусочков')),
                ('isSale', models.BooleanField(default=False, verbose_name='Наличие скидки')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('oldPrice', models.IntegerField(null=True, verbose_name='Старая цена')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
        ),
    ]
